{{- if .Values.vault.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.app.name }}-spc"
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  provider: vault
  parameters:
    vaultAddress: {{ .Values.vault.address | quote }}
    vaultKubernetesMountPath: "kubernetes"
    audience: "vault"
    roleName: {{ .Values.vault.role | quote }}
    objects: |
      - objectName: "secret"
        secretPath: {{ include "microservice.vaultSecretPath" . | quote }}
{{- end }}
