{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microservice.serviceAccountName" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  {{- if or .Values.serviceAccount.annotations .Values.serviceAccount.roleArn (and .Values.serviceAccount.irsa .Values.serviceAccount.irsa.enabled) }}
  annotations:
    {{- if .Values.serviceAccount.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn | quote }}
    {{- else if and .Values.serviceAccount.irsa .Values.serviceAccount.irsa.enabled }}
    eks.amazonaws.com/role-arn: {{ include "microservice.irsaRoleArn" . | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
